import { Suspense } from "react";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import LoadingSpinner from "./components/LoadingSpinner";
import ScrollToTop from "./components/ScrollToTop";

// Load Poppins font with specified weights
const poppins = Poppins({
  weight: ["400", "600", "700"], // You can adjust the weights based on your requirements
  subsets: ["latin"], // Only include the necessary subset (e.g., latin)
  variable: "--font-poppins", // Custom CSS variable for Poppins font
});

export const metadata = {
  title: "Hirdo Portfolio",
  description: "Generated by Hirdo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* Use the poppins constant here */}
      <body className={poppins.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <ScrollToTop />
        <Suspense fallback={null}>
          <LoadingSpinner />
        </Suspense>
      </body>
    </html>
  );
}
